import type { JSONSchema7 } from 'json-schema';
import generated from './singbox-schema.generated.json';

/**
 * sing-box config schema for the editor.
 *
 * The file `singbox-schema.generated.json` is generated by the script
 * `scripts/gen-singbox-schema.mjs` (`task schema:update`) from two sources: the
 * official sing-box schema and its own documentation, from which the descriptions
 * are taken — the schema itself has none. Manual texts for frequently edited
 * fields live in `scripts/singbox-schema-overlay.mjs`.
 *
 * The schema tracks 1.14-dev, while the app supports 1.10.7–1.13.x
 * (see `SINGBOX_MIN`/`SINGBOX_MAX_EXCLUSIVE` in `src-tauri/src/clash/client.rs`), so
 * on older syntax it may complain where sing-box itself has no objections. This is
 * intentional: schema errors are a hint in the editor; saving is gated only by
 * `sing-box check` (`api.checkSingboxConfig` → `commands.rs::check_singbox_config`).
 */
// Via `unknown`: TypeScript infers an exact literal type from the JSON import for the
// whole file, and the mutually exclusive fields of oneOf variants get `undefined`,
// which does not fit JSONSchema7's index signature directly.
export const singboxSchema = generated as unknown as JSONSchema7;
